### ISSUE TITLE
[Regression] The attachments list is not displayed on XWiki 14.4.3 (error loading data)

### ISSUE THREAD

**Issue by lucaa** [xwikisas/xwiki-pro-macros#131]
How to reproduce:
* on XWiki 14.4.3 create a page, add attachments
* install pro macros version 1.8
* call `{{confluence_attachments /}}` on the page with attachments

Expected result: the attachments of the page are displayed, in a list or a table

Actual result: a livedata is displayed, but with 0 entries and an error at the bottom of the screen says that the data could not be loaded.

Here is a screenshot of this, in a wiki in french:

![image](https://github.com/xwikisas/xwiki-pro-macros/assets/657716/a9b570f5-6f03-49db-ab43-50c076404e99)

**Note:** this is a **regression**, on the same XWiki version with Pro macros version 1.6 this was working, the attachments were displayed (not as a livedata, but the display was working).

**Comment by ClemDee** [comment]
The attachments list is not displayed on the Livedata because 14.4.3 does not use the Livedata to display attachements on standard panels / views. As the code of the Attachement macro reuses code from the `attachment_macro.vm` vm, that's why it does not find the required macros and fail.

I can see two solutions:
* Do not depend on standard xwiki code and copy all the needed macros inside the attachement macro so that it works independently of the XWiki version. Drawbacks: there would be quite a lot of code to be copied, and it would not work on XWiki versions prior to the LD addition.
* Use the old attachement macro for that 14.4.3 version and all other versions that do not use the LD to display attachements natively. I guess this can be done programmatically in the code, or by setting up dependencies in the configuration (but I'm not sure about this option as the macro does not come as a standalone but bundled). Drawbacks: two different versions of the macro to maintain, possible user confusion, implementation more complex

Maybe there is another option that I didn't see.

@snazare what strategy do you recommend?

**Comment by mflorea** [comment]
We have to support both cases until we upgrade the parent to a version of XWiki that uses live data for attachments. That's not the case right now, as the parent is 13.10 where we don't use live data for attachments. So we need to detect if live data or live table is used and adapt. Normally we try the newest feature first, i.e. try to use live data, and if we detect it's not present then fallback on the older feature (live table). I guess that's option 2.

**Comment by oanalavinia** [comment]
The attachments macro is working now for older versions as well.
The only limitation is that for versions of XWiki older than 14.4, the attachment upload and delete actions will trigger a page reload, instead of only a livedata reload as it happens on newer versions (because of an API limitation).
