### ISSUE TITLE
Viewpdf macro cannot be used inline

### ISSUE THREAD

**Issue by ClemensRobbenhaar** [xwikisas/xwiki-pro-macros#157]
The `viewpdf` macro cannot be used inline.
This seems obvious, as displaying a PDF inline makes no sense.

However the `viewpdf` can appear inline in pages migrated from confluence. The migrated pages then just show an error message.
A possible workaround is to allow this macro to be used "inline" by adding a container `(((...)))` around them. This of course interrupts the inline flow of the surrounding text, but makes he macro usable.  
As the likely reasons why the macro has been used inline from confluence is just a missing line break or the like, I think this is an acceptable solution.

PR is following.

**Comment by ClemensRobbenhaar** [comment]
[See PR#158](https://github.com/xwikisas/xwiki-pro-macros/pull/158)

**Comment by mflorea** [comment]
@ClemensRobbenhaar can you give us an example of XWiki syntax that is generated as a result of the Confluence migration where the ``viewpdf`` appears inline? I'd like to understand why the ``viewpdf`` is inline because, as you correctly noted, it doesn't make sense to have it inline.

The solution you propose is a workaround. You're avoiding the effect, but not fixing the root cause. Moreover, saying that the macro supports inline mode when it actually generates block level content (DIV, as a result of using the group wiki syntax ``(((...)))``) is not right. Same, the following IF is not semantically right:

    #if ($xcontext.macro.context.isInline())(((#end

This translates to "if the context is inline then generate a block level element", which doesn't make sense.

I'd like to understand why the ``viewpdf`` ends up inline after the migration, because this may be something that we can fix in the migrator / filter stream.

**Comment by snazare** [comment]
Closing as inactive. We will need an example file to reproduce and fix the issue.
