### ISSUE TITLE
Content Report Table Macro - Adding more then 1 space doesn't show any results

### ISSUE THREAD

**Issue by ane-gabriela** [xwikisas/xwiki-pro-macros#47]
Preconditions: Add tags to different pages on the wiki, in different spaces.

Steps to reproduce:
1. Edit a page
1. Click on Insert > Other macros 
1. Search and select Content Report Table Macro
1. Add in the Labels text box tags added in other pages and other spaces, separated by comma eg. "test1,qa,xwiki"
1. Add 2 of the spaces separate by comma eg. Space1,Space2
1. Click on Save & View

Expected results: List of pages that have the selected tags are shown in a table.

Actual results: No result is shown.
NOTE: When adding the spaces 1 by one results are showing, when adding them both nothing appears.

![SpacesNoResult](https://user-images.githubusercontent.com/40691112/113448766-1f8cca80-9405-11eb-907a-769fd2cc390c.png)

Environment: Windows 10, IE 11, XWiki 12.10.4 with MySQL 8.0 and xwiki-pro-macros 1.0-RC1

**Comment by acotiuga** [comment]
Problems identified:
* for more than one space, the hql syntax was broken because the `OR` operand was added only after the second space comparison
* `doc.space like ?doc.space like ?` was wrongly generated instead of `doc.space like ? OR doc.space like ?`
* another problem was that `concat(".%")` is skipping the first level children, so `A.WebHome` was never displayed, only `A.%.WebHome`
Also I updated the parameters description to be clear that the separator for the spaces parameter is comma followed by blank space: `Main, XWiki` and not `Main,XWiki`
If the page name contains space followed by comma, there's nothing we can do, unless we change the separator, but then the macro won't be compatible with Confluence macro anymore.
