### ISSUE TITLE
Section Macro - Show Border appears as 0 by default in macro and doesn't work

### ISSUE THREAD

**Issue by ane-gabriela** [xwikisas/xwiki-pro-macros#48]
Steps to reproduce:

1. Edit a page
2. Click on Insert > Other macros 
3. Search and select Section Macro
4. Observe the default value in the Show Border ![Border Options](https://user-images.githubusercontent.com/40691112/113576151-b1741d80-9627-11eb-8888-6d61766fa707.png)
5. Add Show Border true
6. Click on Submit

Expected results: As per https://confluence-migrator.devxwiki.com/xwiki/bin/view/Confluence/Macros/Section the Show Border parameter is **false** or **true**. The macro is added with the border selected.

Actual results: In XWiki the Show Border appears as 0, and doesn't show any border when added with 0 or true.

Environment: Windows 10, IE 11, XWiki 12.10.4 with MySQL 8.0 and xwiki-pro-macros 1.0-RC1

**Comment by acotiuga** [comment]
The Section macro needs to be compatible with https://confluence.atlassian.com/doc/section-macro-51872531.html, which has a note **Note: Without a Column macro , the border will not be displayed correctly.**. In practice it may not be displayed at all. 
I updated the documentation to remove this expectation, as the border is applied to the columns added in the section, not to the section itself., which is related to the way this macro should be used **in conjunction with the Column macro**, which mean that it doesn't really make sense to have the section without the columns.
The default value in the macro shows now `false` instead of `0`
